interface Manifest {
  version: string;
  base: string;
  navigationFallback: string | false;
  assets: {url: string; revision: string}[];
}

const generated = '// Generated by tinyjoinOffline.\n';

export const registrationSource = (): string => `${generated}
(() => {
  if (!('serviceWorker' in navigator)) return;
  const base = new URL('.', document.currentScript.src);
  const worker = new URL('tinyjoin-sw.js', base).href;
  navigator.serviceWorker.getRegistration(base.href).then((existing) => {
    const current = existing && (existing.active || existing.waiting || existing.installing);
    if (current && current.scriptURL !== worker) {
      console.warn('TinyJoin offline registration skipped: an existing service worker owns this application. Use tinyjoinOffline({mode: "manifest"}) to integrate its cache.');
      return;
    }
    return navigator.serviceWorker.register(worker, {scope: base.href, updateViaCache: 'none'});
  }).catch((error) => console.warn('TinyJoin offline installation failed:', error));
})();
`;

export const serviceWorkerSource = (): string => `${generated}
importScripts('./tinyjoin-precache.js');
const precache = self.createTinyjoinPrecache();
self.addEventListener('install', (event) => event.waitUntil(precache.install()));
self.addEventListener('activate', (event) => event.waitUntil(precache.activate()));
self.addEventListener('fetch', (event) => {
  const response = precache.match(event.request);
  if (response) event.respondWith(response);
});
`;

export const helperSource = (manifest: Manifest): string => `${generated}
(() => {
  const manifest = ${JSON.stringify(manifest)};
  self.createTinyjoinPrecache = (baseUrl) => {
    const base = new URL(baseUrl || (manifest.base.startsWith('/') ? manifest.base : self.registration.scope), self.location.origin);
    if (base.origin !== self.location.origin || !base.pathname.endsWith('/')) {
      throw new Error('TinyJoin precache base must be a same-origin directory URL');
    }
    const prefix = 'tinyjoin-offline:' + encodeURIComponent(base.href) + ':';
    const cacheName = prefix + manifest.version;
    const urls = new Map(manifest.assets.map((asset) => [new URL(asset.url, base).href, asset.revision]));
    const fallback = manifest.navigationFallback === false ? undefined : new URL(manifest.navigationFallback, base).href;
    const fetchVerified = async (url, revision) => {
      const response = await fetch(new Request(url, {cache: 'reload', credentials: 'same-origin'}));
      if (!response.ok) throw new Error('HTTP ' + response.status + ' for ' + url);
      const digest = await crypto.subtle.digest('SHA-256', await response.clone().arrayBuffer());
      const actual = Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, '0')).join('');
      if (actual !== revision) throw new Error('Build changed during offline installation: ' + url);
      return response;
    };
    return {
      async install() {
        const cache = await caches.open(cacheName);
        const pending = [...urls];
        let failed;
        await Promise.all(Array.from({length: Math.min(8, pending.length)}, async () => {
          while (!failed && pending.length) {
            const [url, revision] = pending.shift();
            try {
              await cache.put(url, await fetchVerified(url, revision));
            } catch (error) { failed = error; }
          }
        }));
        if (failed) {
          await caches.delete(cacheName);
          throw failed;
        }
      },
      async activate() {
        // Native waiting keeps the previous worker and cache alive until its clients close.
        // Existing-worker integrations must preserve this lifecycle too.
        await Promise.all((await caches.keys()).filter((key) => key.startsWith(prefix) && key !== cacheName).map((key) => caches.delete(key)));
      },
      match(request) {
        if (request.method !== 'GET') return;
        const url = new URL(request.url);
        if (url.origin !== base.origin || !url.pathname.startsWith(base.pathname)) return;
        let key = url.href;
        if (request.mode === 'navigate') {
          url.search = '';
          url.hash = '';
          key = url.href;
          if (url.pathname.endsWith('/')) key += 'index.html';
          if (!urls.has(key)) key = fallback;
        }
        if (!key || !urls.has(key)) return;
        return caches.open(cacheName).then(async (cache) => {
          const response = await cache.match(key);
          if (response) return response;
          try {
            // Repair eviction only with this release's verified bytes, never a newer deployment.
            const repaired = await fetchVerified(key, urls.get(key));
            await cache.put(key, repaired.clone());
            return repaired;
          } catch {
            return new Response('The offline application cache is incomplete. Close all application tabs and reopen online.', {status: 503});
          }
        });
      },
    };
  };
})();
`;
